version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  node-app:
    build: ./node-app
    image: junnkrd/node-app:latest
    container_name: node-app
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nodedb
      - MYSQL_PASSWORD=root
    networks:
      - node-network
    volumes:
      - ./node-app:/app
      - /app/node_modules
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "30s", "npm", "start"]

  nginx:
    build: ./nginx
    image: junnkrd/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node-app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
    
volumes:
  mysql-data:
    driver: local
